conf = {
    "games_filter": "new",
    #  "data_updates": ['Name', 'OG name', 'bgg_id', 'bgg_url', 'bgg_rating', 'Num players', 'In BBB', 'In Svet Her', 'In Tlama Showroom', 'In BGA', 'Youtube', 'Youtube SUSD', 'Youtube Dice Tower', 'Tlama'],
    "data_updates": [
        "Name",
        "OG name",
        "bgg_id",
        "bgg_url",
        "bgg_rating",
        "Num players",
        "In BBB",
        "In Svet Her",
        "In Tlama Showroom",
        "In BGA",
        "Youtube",
        "Youtube SUSD",
        "Youtube Dice Tower",
        "Tlama",
        "Tabletop Finder",
    ],
    "games_filters": ["new", "all", "id", "bgg_id", "all_including_bought_passed"],
    "bgg_id": 232830,
    "all_updates": [
        "Name",
        "OG name",
        "bgg_id",
        "bgg_url",
        "bgg_rating",
        "Num players",
        "In BBB",
        "In Svet Her",
        "In Tlama Showroom",
        "In BGA",
        "Youtube",
        "Youtube SUSD",
        "Youtube Dice Tower",
        "Tlama",
        "Tabletop Finder",
    ],
}
